name: Build & Deploy QA1

on:
  workflow_run:
    workflows: ["Run CSX QA1"]
    types: [completed]
    branches: ["developer/berdugo"]   # solo se dispara si el workflow previo corrió en esta rama

env:
  PROJECT_PATH: "RadioQ10/RadioQ10.csproj"
  PUBLISH_DIR: "publish"
  FTP_HOST: ${{ secrets.FTP_HOST }}
  FTP_USER: ${{ secrets.FTP_USER }}
  FTP_PASS: ${{ secrets.FTP_PASS }}
  FTP_DIR: ${{ secrets.FTP_DIR_QA1 }}

jobs:
  build-and-deploy:
    # Asegura que solo corra si el workflow previo fue exitoso
    # y refuerza que la rama sea la esperada
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'developer/berdugo' }}
    runs-on: ubuntu-latest

    steps:
      - name: Info del run que disparó este workflow
        run: |
          echo "Workflow previo: ${{ github.event.workflow_run.name }}"
          echo "Rama: ${{ github.event.workflow_run.head_branch }}"
          echo "SHA : ${{ github.event.workflow_run.head_sha }}"

      - name: Checkout (exactamente el commit del workflow que terminó)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Clean
        run: dotnet clean "$PROJECT_PATH" -c Release

      - name: Restore (runtime win-x86)
        run: dotnet restore "$PROJECT_PATH" -r win-x86

      - name: Build (Release, net9.0, win-x86)
        run: dotnet build "$PROJECT_PATH" -c Release -f net9.0 -r win-x86 --no-restore

      - name: Publish (net9.0 | win-x86 | framework-dependent)
        run: |
          dotnet publish "$PROJECT_PATH" \
            --configuration Release \
            --framework net9.0 \
            --self-contained false \
            -p:PublishSingleFile=false \
            -p:GenerateRuntimeConfigurationFiles=true \
            --output "$PUBLISH_DIR"

      # ----- Deploy FTP -----
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ env.FTP_HOST }}     # sin "ftp://"
          username: ${{ env.FTP_USER }}
          password: ${{ env.FTP_PASS }}
          protocol: ftp
          local-dir: ./publish/
          server-dir: ${{ env.FTP_DIR }}
          exclude: |
            **/*.pdb
            **/*.xml
